# file: system/docker-compose-src.yaml v2.7
services:
  builder-src-openwrt:
    build:
      context: ..
      dockerfile: system/src.dockerfile
    # FIX: Добавляем и сюда для страховки от строгих ядер
    security_opt:
      - seccomp:unconfined
    user: "root"
    environment:
      - CONF_FILE=${SELECTED_CONF}
      - CCACHE_DIR=/ccache
    volumes:
      - src-workdir:/home/build/openwrt
      - src-dl-cache:/home/build/openwrt/dl
      - src-ccache:/ccache
      - ../profiles:/profiles${ROUTERFW_BIND_PROFILES_SUFFIX:-}
      - ../${HOST_PKGS_DIR}:/input_packages${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../${HOST_PATCHES_DIR}:/patches${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../${HOST_FILES_DIR}:/overlay_files${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../${HOST_OUTPUT_DIR}:/output${ROUTERFW_BIND_RW_SUFFIX:-}
      - ./openssl.cnf:/openssl.cnf${ROUTERFW_BIND_RO_SUFFIX:-}
      - ./src_builder.sh:/src_builder.sh${ROUTERFW_BIND_RO_SUFFIX:-}
    command: /bin/bash /src_builder.sh

  builder-src-oldwrt:
    build:
      context: ..
      dockerfile: system/src.dockerfile.legacy
    # FIX: Критически важно для Ubuntu 18.04 container on Ubuntu 24.04 Host
    security_opt:
      - seccomp:unconfined
    user: "root"
    environment:
      - CONF_FILE=${SELECTED_CONF}
      - CCACHE_DIR=/ccache
    volumes:
      - src-workdir:/home/build/openwrt
      - src-dl-cache:/home/build/openwrt/dl
      - src-ccache:/ccache
      - ../profiles:/profiles${ROUTERFW_BIND_PROFILES_SUFFIX:-}
      - ../${HOST_PKGS_DIR}:/input_packages${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../${HOST_PATCHES_DIR}:/patches${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../${HOST_FILES_DIR}:/overlay_files${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../${HOST_OUTPUT_DIR}:/output${ROUTERFW_BIND_RW_SUFFIX:-}
      - ./openssl.cnf:/openssl.cnf${ROUTERFW_BIND_RO_SUFFIX:-}
      - ./src_builder.sh:/src_builder.sh${ROUTERFW_BIND_RO_SUFFIX:-}
    command: /bin/bash /src_builder.sh

volumes:
  src-dl-cache:
  src-workdir:
  src-ccache:
# checksum:MD5=b5e4d17239954816f8f0fe56b27275dc