# file: system/docker-compose.yaml V1.8
services:
  builder-openwrt:
    build:
      context: ..
      dockerfile: system/dockerfile
    environment:
      - CONF_FILE=${SELECTED_CONF}
      - HOST_OUTPUT_DIR=${HOST_OUTPUT_DIR}
    volumes:
      - imagebuilder-cache:/cache
      - ipk-cache:/builder_workspace/dl
      - ../${HOST_PKGS_DIR}:/input_packages${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../${HOST_FILES_DIR}:/overlay_files${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../firmware_output:/output${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../profiles:/profiles${ROUTERFW_BIND_PROFILES_SUFFIX:-}
      - ./openssl.cnf:/openssl.cnf${ROUTERFW_BIND_RO_SUFFIX:-}
      - ./ib_builder.sh:/ib_builder.sh${ROUTERFW_BIND_RO_SUFFIX:-}
    command: /bin/bash /ib_builder.sh

  builder-oldwrt:
    build:
      context: ..
      dockerfile: system/dockerfile.legacy
    environment:
      - CONF_FILE=${SELECTED_CONF}
      - HOST_OUTPUT_DIR=${HOST_OUTPUT_DIR}
    volumes:
      - imagebuilder-cache:/cache
      - ipk-cache:/builder_workspace/dl
      - ../${HOST_PKGS_DIR}:/input_packages${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../${HOST_FILES_DIR}:/overlay_files${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../firmware_output:/output${ROUTERFW_BIND_RW_SUFFIX:-}
      - ../profiles:/profiles${ROUTERFW_BIND_PROFILES_SUFFIX:-}
      - ./openssl.cnf:/openssl.cnf${ROUTERFW_BIND_RO_SUFFIX:-}
      - ./ib_builder.sh:/ib_builder.sh${ROUTERFW_BIND_RO_SUFFIX:-}
    command: /bin/bash /ib_builder.sh

volumes:
  imagebuilder-cache:
  ipk-cache:
# checksum:MD5=d9d004c701fa3984aa1772a94376f7d3