# file: system/podman-compose.yaml
services:
  builder-openwrt:
    user: "0:0"
    userns_mode: "keep-id:uid=0,gid=0"

  builder-oldwrt:
    user: "0:0"
    userns_mode: "keep-id:uid=0,gid=0"
# checksum:MD5=1c5ea163494874de5f56727786adcdf8